var namespace_s_p_q =
[
    [ "controller", "namespace_s_p_q_1_1controller.html", "namespace_s_p_q_1_1controller" ],
    [ "dao", "namespace_s_p_q_1_1dao.html", "namespace_s_p_q_1_1dao" ],
    [ "data", "namespace_s_p_q_1_1data.html", "namespace_s_p_q_1_1data" ],
    [ "dto", "namespace_s_p_q_1_1dto.html", "namespace_s_p_q_1_1dto" ],
    [ "gateway", "namespace_s_p_q_1_1gateway.html", "namespace_s_p_q_1_1gateway" ],
    [ "gui", "namespace_s_p_q_1_1gui.html", "namespace_s_p_q_1_1gui" ],
    [ "main", "namespace_s_p_q_1_1main.html", "namespace_s_p_q_1_1main" ],
    [ "remote", "namespace_s_p_q_1_1remote.html", "namespace_s_p_q_1_1remote" ],
    [ "ClientTest", "class_s_p_q_1_1_client_test.html", "class_s_p_q_1_1_client_test" ],
    [ "CoberturaTest", "class_s_p_q_1_1_cobertura_test.html", "class_s_p_q_1_1_cobertura_test" ],
    [ "DAOMockTest", "class_s_p_q_1_1_d_a_o_mock_test.html", "class_s_p_q_1_1_d_a_o_mock_test" ],
    [ "DATAProductTest", "class_s_p_q_1_1_d_a_t_a_product_test.html", "class_s_p_q_1_1_d_a_t_a_product_test" ],
    [ "DATAUserTest", "class_s_p_q_1_1_d_a_t_a_user_test.html", "class_s_p_q_1_1_d_a_t_a_user_test" ],
    [ "EroskiServer", "class_s_p_q_1_1_eroski_server.html", null ],
    [ "EroskiService", "class_s_p_q_1_1_eroski_service.html", "class_s_p_q_1_1_eroski_service" ],
    [ "FacebookServer", "class_s_p_q_1_1_facebook_server.html", null ],
    [ "FacebookService", "class_s_p_q_1_1_facebook_service.html", "class_s_p_q_1_1_facebook_service" ],
    [ "GoogleServer", "class_s_p_q_1_1_google_server.html", null ],
    [ "GoogleService", "class_s_p_q_1_1_google_service.html", "class_s_p_q_1_1_google_service" ],
    [ "NeverEmptyServer", "class_s_p_q_1_1_never_empty_server.html", "class_s_p_q_1_1_never_empty_server" ],
    [ "NeverEmptyServerManager", "class_s_p_q_1_1_never_empty_server_manager.html", null ],
    [ "PaypalServer", "class_s_p_q_1_1_paypal_server.html", null ],
    [ "PaypalService", "class_s_p_q_1_1_paypal_service.html", "class_s_p_q_1_1_paypal_service" ],
    [ "RMITest", "class_s_p_q_1_1_r_m_i_test.html", "class_s_p_q_1_1_r_m_i_test" ],
    [ "Utilities", "class_s_p_q_1_1_utilities.html", "class_s_p_q_1_1_utilities" ],
    [ "VisaServer", "class_s_p_q_1_1_visa_server.html", null ],
    [ "VisaService", "class_s_p_q_1_1_visa_service.html", "class_s_p_q_1_1_visa_service" ]
];